### ISSUE TITLE
Everything is `undefined`

### ISSUE THREAD

**Issue by ShafSpecs** [xan105/node-nodeRT#3]
Hello 👋, using this is an electron file. I get error that a particular constructor is `undefined`. Logging that particular namespace yielded a lot of undefined objects:
```ts
[Module: null prototype] {
  AltitudeReferenceSystem: undefined,
  CivicAddress: undefined,
  GeoboundingBox: undefined,
  Geocircle: undefined,
  Geocoordinate: undefined,
  GeocoordinateSatelliteData: undefined,
  GeolocationAccessStatus: undefined,
  Geolocator: undefined,
  // ...
}
``` 
I am using electron v30, and the `*.node` files seem in order. I am not sure whether I was meant to do something first or I am just doing it wrong

**Comment by xan105** [comment]
As stated in the readme some namespace export might be `undefined` due to missing corresponding .node nodert file (compilation failure, etc). 

Could you tell me which WinRT namespace we are talking about here? This might also be an error on my end. I'll go check. Most is auto or semi auto generated due to the amount of namespace, errors are possible. 

NB: Also did you install the electron targeted build ? 
```npm i @xan105/nodert --electron```
cf: https://github.com/xan105/node-nodeRT?tab=readme-ov-file#electron

**Comment by ShafSpecs** [comment]
I did not add the electron flag, would confirm if that's the issue atm. But I used the npm_config variable. I am using windows.devices.geolocation

I would test it with electron flag now and get back to you. Thank you :)

**Comment by ShafSpecs** [comment]
Looks like that caused the undefined thingy, the `prebuilds` folder had node prebuilds. Deleting it and re-installing with the flag, fixed it. Thank you 😄! 

*I think the part about adding the flag should be more explicit, I thought it was one of the two: `_nodert` in `package.json` or flag*
