### ISSUE TITLE
yarn compatibility

### ISSUE THREAD

**Issue by inshatan** [xan105/node-nodeRT#7]
thank you for the package!

no `modules` argument, no `_nodert/modules` path in package.json are working with yarn( could you add a support for yarn v1 also?

**Comment by xan105** [comment]
I'm not familiar with `yarn` tho I gave it a quick shot to see if I had your issues.

This package uses a npm install script to fetch the precompiled modules from Github.
The script is run and precompiled `.node` files can be found in `node_modules/@xan105/nodeRT/prebuilds`

But, indeed passing a list of modules to keep does not work as expected.
The issue seems to be that `npm_config_*` env var are not set by `yarn`.

cf: https://github.com/yarnpkg/yarn/issues/4581

_I will investigate further but I'm not sure there is anything I can do to fix it._

**Comment by inshatan** [comment]
I have created PR to support yarn, could you please take a look
https://github.com/xan105/node-nodeRT/pull/8

**Comment by xan105** [comment]
LGTM
This should allow passing a list of modules via package.json `_nodert/modules` property with yarn
I've released v2.2.1 with aforementioned PR
